- connection: local
  gather_facts: false
  hosts: localhost
  tasks:
  - cisco.dnac.template_workflow_manager:
      config:
      - configuration_templates:
          device_types:
          - product_family: '{{ item.family }}'
          language: '{{ item.language }}'
          project_name: '{{ item.proj_name }}'
          software_type: '{{ item.type }}'
          template_content: '{{ item.device_config }}'
          template_name: '{{ item.temp_name }}'
          version_description: '{{ item.description }}'
        deploy_template:
          device_details:
            device_hostnames: '{{ item.device_details.device_hostnames }}'
          force_push: '{{ item.force_push }}'
          project_name: '{{ item.proj_name }}'
          site_provisioning_details:
          - device_family: '{{ item.site_provisioning_details.device_family }}'
            device_role: '{{ item.site_provisioning_details.device_role }}'
            device_tag: '{{ item.site_provisioning_details.device_tag }}'
            site_name: '{{ item.site_provisioning_details.site_name }}'
          template_name: '{{ item.temp_name }}'
          template_parameters:
          - param_name: '{{ item.template_parameters.param_name }}'
            param_value: '{{ item.template_parameters.param_value }}'
          - param_name: '{{ item.template_parameters.param_name }}'
            param_value: '{{ item.template_parameters.param_value }}'
        export:
          project:
          - Ansible_project
          - Sample Velocity Templates
          template:
          - project_name: Onboarding Configuration
            template_name: AP_Onboarding
        import:
          project: '{{ item.import_project }}'
          template: '{{ item.import_template }}'
      config_verify: true
      dnac_debug: '{{ dnac_debug }}'
      dnac_host: '{{ dnac_host }}'
      dnac_log: false
      dnac_log_append: true
      dnac_log_level: DEBUG
      dnac_password: '{{ dnac_password }}'
      dnac_port: '{{ dnac_port }}'
      dnac_username: '{{ dnac_username }}'
      dnac_verify: '{{ dnac_verify }}'
      dnac_version: '{{dnac_version}}'
      state: merged
      validate_response_schema: false
    name: Test project template
    register: template_result
    tags:
    - template
    with_items: '{{ template_details }}'
  vars_files:
  - credentials.yml
  - device_details.template
